// Package slackoverflow - This is autogenerated file. To Regenerate contributors list run (make contributors)
package slackoverflow

var contributors = []string{
  "Marko Kungla marko.kungla@gmail.com",
}
